version: '3'
services:
  mysql:
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mydbddl.sql:/docker-entrypoint-initdb.d/mydbddl.sql
#      - ./mysql-data:/var/lib/mysql

